services:
  - type: web
    name: wbot-whatsapp
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        fromGroup: shared-supabase-settings
      - key: SUPABASE_ANON_KEY
        fromGroup: shared-supabase-settings
      - key: SESSION_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PUBLIC_URL
        sync: false
